export const  user ={
  "login": "theallegrarr",
  "id": 17985620,
  "node_id": "MDQ6VXNlcjE3OTg1NjIw",
  "avatar_url": "https://avatars3.githubusercontent.com/u/17985620?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/theallegrarr",
  "html_url": "https://github.com/theallegrarr",
  "followers_url": "https://api.github.com/users/theallegrarr/followers",
  "following_url": "https://api.github.com/users/theallegrarr/following{/other_user}",
  "gists_url": "https://api.github.com/users/theallegrarr/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/theallegrarr/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/theallegrarr/subscriptions",
  "organizations_url": "https://api.github.com/users/theallegrarr/orgs",
  "repos_url": "https://api.github.com/users/theallegrarr/repos",
  "events_url": "https://api.github.com/users/theallegrarr/events{/privacy}",
  "received_events_url": "https://api.github.com/users/theallegrarr/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Nurudeen Amedu",
  "company": null,
  "blog": "www.finepreent.com",
  "location": "Earth",
  "email": null,
  "hireable": null,
  "bio": "MQL4 || MQL5 || cAlgo",
  "public_repos": 55,
  "public_gists": 1,
  "followers": 2,
  "following": 5,
  "created_at": "2016-03-21T14:29:46Z",
  "updated_at": "2019-10-01T13:54:48Z"
}